### ISSUE TITLE
Peer Testing Report - Participant Details (Everyone)

### ISSUE THREAD

**Issue by geraldjet** [GreyWolfSif/COSC499Project#44]
Identify the number of participants that completed your study. In particular, include a table of participant's name, status (completed, partially completed, no show, type of evaluation (user vs. thinkaloud)). For incomplete and no show statuses, provide an explanation. Indicate who ran each session and who the participant was. (only for those that run the sessions remote) Links to all the videos that were recorded.

**Comment by GreyWolfSif** [comment]
handed in this assignment last semester
